FROM openjdk:latest
LABEL maintainer="javaguides.net"
ADD ./build/libs/RegisterTraineeModule-0.0.1-SNAPSHOT.jar springboot-docker-demo.jar
#EXPOSE 5678
ENTRYPOINT ["java", "-jar", "springboot-docker-demo.jar"]